//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblKomadNamestaja
    {
        public int ID { get; set; }
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        [Remote("sifraJedinstvena", "Namestaj", ErrorMessage = "Sifra namestaja je vec u upotrebi!")]
        public string Sifra { get; set; }
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        [Required(ErrorMessage = "Morate uneti naziv.")]
        public string Naziv { get; set; }
        [Required(ErrorMessage = "Morate uneti zemlju porekla.")]
        [Display(Name ="Zemlja porekla")]
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        public string ZemljaProizvodnje { get; set; }
        [Display(Name = "Cena")]
        [Required(ErrorMessage = "Morate uneti cenu.")]
        public decimal JedinicnaCena { get; set; }
        [Display(Name = "Kolicina")]
        [Required(ErrorMessage = "Morate uneti kolicinu.")]


        public int RaspolozivaKolicina { get; set; }
        [Display(Name = "Salon")]
        public int SalonID { get; set; }
        [Display(Name = "Kategorija")]
        public int KategorijaID { get; set; }
        [Required(ErrorMessage = "Morate uneti sliku.")]
       
        public string Slika { get; set; }
    
        public virtual tblKategorija tblKategorija { get; set; }
        public virtual tblSaloni tblSaloni { get; set; }
    }
}
