//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblSaloni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaloni()
        {
            this.tblKomadNamestaja = new HashSet<tblKomadNamestaja>();
        }
    
        public int ID { get; set; }
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        [Required(ErrorMessage = "Morate uneti naziv.")]
        public string Naziv { get; set; }
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        [Required(ErrorMessage = "Morate uneti vlasinika.")]
        public string Vlasnik { get; set; }
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        [Required(ErrorMessage = "Morate uneti Adresa.")]
        public string Adresa { get; set; }
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        [Required(ErrorMessage = "Morate uneti telefon.")]
        public string Telefon { get; set; }
        [StringLength(50, ErrorMessage = "Maksimum 40 karaktera")]
        [Required(ErrorMessage = "Morate uneti e-mail.")]
        public string Email { get; set; }
        [Display(Name ="Web stranica")]
        public string WebStranica { get; set; }
        [Remote("pibJedinstvena", "Saloni", ErrorMessage = "Taj PIB je u upotrebi!")]
        public int PIB { get; set; }
        [Remote("brojRacunaJedinstven", "Saloni", ErrorMessage = "Ziro racun je vec u upotrebi!")]
        [Display(Name = "Broj ziro racuna")]

        public int BrojZiroRacuna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKomadNamestaja> tblKomadNamestaja { get; set; }
    }
}
