//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStavkeNaRacunu
    {
        public int ID { get; set; }
        public int RacunID { get; set; }
        public int StavkaID { get; set; }
    
        public virtual tblRacun tblRacun { get; set; }
        public virtual tblStavke tblStavke { get; set; }
    }
}
